# Development environment overrides
_environment: development

global:
  log_level: DEBUG

gdb:
  processing:
    compression_level: 2


database:
  path: "data/dev_gdb_metadata.duckdb"

# Development-specific SDE instances could go here if different