# Development environment overrides


global:
  log_level: DEBUG
  s3:
    bucket: "gcover-assets-dev"
    profile: "gcover_bucket"  # AWS profile name




gdb:
  base_paths:
    backup: "/home/marco/DATA/GCOVER"
    verification: "/home/marco/DATA/Verifications"
    increment: "/home/marco/DATA/Increment"
  db_path: "data/dev_gdb_metadata.duckdb"




# Development-specific SDE instances could go here if different