# src/gcover/publish/__init__.py
"""
GeoCover data publish modules.

This package provides tools for enriching lightweight GeoCover datasets
(like geocover_tooltips) with information from original RC databases
through intelligent spatial matching.
"""

from gcover.publish.esri_classification_applicator import (
    ClassificationApplicator,
    ClassificationMatcher,
    LayerMapping,
    apply,
    apply_classification_to_gdf,
    apply_classification_to_gpkg,
    apply_robust_filter,
    cast_geodataframe_fields,
    check,
    cli,
    create_mapping,
    display_classification_summary,
    float_to_int_string,
    get_numeric_field_names,
    get_numeric_fields_from_dataframe,
    validate_field_types,
)
from gcover.publish.esri_classification_extractor import (
    CIMColorParser,
    CIMSymbolParser,
    CIMSymbolParserEnhanced,
    ClassificationClass,
    ClassificationDisplayer,
    ClassificationJSONEncoder,
    ColorInfo,
    ESRIClassificationExtractor,
    ESRIClassificationExtractorEnhanced,
    FieldInfo,
    LayerClassification,
    SymbolInfo,
    SymbolType,
    apply_overrides_to_classification,
    classify,
    explore_layer_structure,
    export_classifications_to_csv,
    export_classifications_to_json,
    export_complete_classification_to_json,
    extract_lyrx_complete,
    generate_override_template,
    to_serializable_dict,
    truncate_label,
)
from gcover.publish.generator import MapServerGenerator, QGISGenerator
from gcover.publish.merge_sources import (
    GDBMerger,
    MergeConfig,
    MergeStats,
    SourceConfig,
    SourceType,
    create_merge_config,
    extract_geometries_by_type,
    force_2d,
    get_expected_geometry_type,
    normalize_geodataframe_geometries,
    normalize_geometry,
)
from gcover.publish.style_config import (
    BatchClassificationConfig,
    ClassificationConfig,
    FontSymbol,
    LayerConfig,
    apply_batch_from_config,
    apply_config,
    cli,
    create_config,
)
from gcover.publish.symbol_models import (
    CharacterMarkerInfo,
    ClassIdentifier,
    FillType,
    FontSymbol,
    GradientFillInfo,
    HatchFillInfo,
    PictureFillInfo,
    SymbolLayersInfo,
    SymbolOverride,
    SymbolOverrideRegistry,
)
from gcover.publish.tooltips_enricher import (
    EnhancedTooltipsEnricher,
    EnrichmentConfig,
    LayerMapping,
    create_enrichment_config,
)
from gcover.publish.vectorized_classification import (
    ClassificationStats,
    LayerClassificationReport,
    VectorizedClassificationApplicator,
    analyze_unclassified_features,
    apply_batch_classifications_vectorized,
    apply_batch_from_config_vectorized,
    build_lookup_table,
    extract_filter_fields,
    normalize_join_column,
    validate_filter_fields,
)

__all__ = [
    "EnhancedTooltipsEnricher",
    "EnrichmentConfig",
    "create_enrichment_config",
    "MapServerGenerator",
    "QGISGenerator",
    # Extractor
    "SymbolType",
    "ColorInfo",
    "SymbolInfo",
    "truncate_label",
    "ClassificationClass",
    "FieldInfo",
    "LayerClassification",
    "ClassificationJSONEncoder",
    "to_serializable_dict",
    "CIMColorParser",
    "CIMSymbolParser",
    "CIMSymbolParserEnhanced",
    "ESRIClassificationExtractor",
    "ESRIClassificationExtractorEnhanced",
    "ClassificationDisplayer",
    "export_classifications_to_json",
    "export_classifications_to_csv",
    "export_complete_classification_to_json",
    "generate_override_template",
    "apply_overrides_to_classification",
    "explore_layer_structure",
    "extract_lyrx_complete",
    "classify"
    # applicator
    "float_to_int_string",
    "get_numeric_field_names",
    "get_numeric_fields_from_dataframe",
    "cast_geodataframe_fields",
    "validate_field_types",
    "apply_robust_filter",
    "LayerMapping",
    "ClassificationMatcher",
    "ClassificationApplicator",
    "apply_classification_to_gdf",
    "apply_classification_to_gpkg",
    "display_classification_summary",
    "cli",
    "apply",
    "create_mapping",
    "check"
    # Symbol models
    "FontSymbol",
    "CharacterMarkerInfo",
    "FillType",
    "HatchFillInfo",
    "PictureFillInfo",
    "GradientFillInfo",
    "SymbolLayersInfo",
    "ClassIdentifier",
    "SymbolOverride",
    "SymbolOverrideRegistry"
    # Merge
    "get_expected_geometry_type",
    "extract_geometries_by_type",
    "normalize_geometry",
    "normalize_geodataframe_geometries",
    "force_2d",
    "SourceType",
    "SourceConfig",
    "MergeConfig",
    "MergeStats",
    "GDBMerger",
    "create_merge_config"
    # Style config
    "FontSymbol",
    "ClassificationConfig",
    "LayerConfig",
    "BatchClassificationConfig",
    "apply_batch_from_config",
    "cli",
    "apply_config",
    "create_config"
    # Vectorized
    "ClassificationStats",
    "LayerClassificationReport",
    "build_lookup_table",
    "normalize_join_column",
    "extract_filter_fields",
    "validate_filter_fields",
    "VectorizedClassificationApplicator",
    "analyze_unclassified_features",
    "apply_batch_classifications_vectorized",
    "apply_batch_from_config_vectorized",
]
