

DB_INSTANCES = ""
SWISS_EPSG = "EPSG:2056"


DEFAULT_OPERATOR = "GC_Import"
DEFAULT_VERSION = "SDE.DEFAULT" # i.e. RC2 or 2030-12-31

DEFAULT_CHUNK_SIZE = 1000 # MAX for ESRI
MANDATORY_FIELDS =  ["OPERATOR", "DATEOFCHANGE"]

# Default extent in EPSG:2056 (LV95 - Swiss projection)
DEFAULT_EXTENT = (
    2485000,
    1070000,
    2835000,
    1290000,
)  # Approx. bounding box for Switzerland


FEAT_CLASSES_SHORTNAMES = {
    "bedrock": "TOPGIS_GC.GC_ROCK_BODIES/TOPGIS_GC.GC_BEDROCK",
    "unco": "TOPGIS_GC.GC_ROCK_BODIES/TOPGIS_GC.GC_UNCO_DESPOSIT",
    "points": "TOPGIS_GC.GC_ROCK_BODIES/TOPGIS_GC.GC_POINT_OBJECTS",
    "sufaces": "TOPGIS_GC.GC_ROCK_BODIES/TOPGIS_GC.GC_SURFACES",
    "lines": "TOPGIS_GC.GC_ROCK_BODIES/TOPGIS_GC.GC_LINEAR_OBJECTS",
    "fossils": "TOPGIS_GC.GC_ROCK_BODIES/TOPGIS_GC.GC_FOSSILS",
}